server {
    listen 80;

    location /api/content/ {
        proxy_pass http://content-service:8000;
    }

    location /api/auth/ {
        proxy_pass http://customer-service:8000;
    }

    location /api/users/ {
        proxy_pass http://customer-service:8000;
    }
}